name: publish

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          cd scroll
          hugo --minify --destination ../public/

      - name: Publish
        uses: bacongobbler/azure-blob-storage-upload@v3.0.0
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          source_dir: 'public'
          container_name: '$web'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          sync: 'true'

